# This code was generated by Claude
#github.py
from typing import TypeAlias
from typing_extensions import TypedDict

InstallationToken: TypeAlias = str
"""Access token for a specific GitHub App installation."""

InstallationId: TypeAlias = str
"""Unique identifier for a GitHub App installation."""

UserAccessToken: TypeAlias = str
"""OAuth access token for making requests on behalf of a user."""

OAuthUrl: TypeAlias = str
"""GitHub OAuth authorization URL."""

OAuthCode: TypeAlias = str
"""Authorization code received from GitHub OAuth callback."""

OAuthState: TypeAlias = str
"""CSRF protection token for OAuth flow validation."""

SHA: TypeAlias = str
"""Git commit SHA hash."""

UserId: TypeAlias = int
"""Unique identifier for a user (GitHub user ID)."""

RepositoryId: TypeAlias = int
"""Unique identifier for a repository (GitHub repository ID)."""

class UserTokens(TypedDict):
    """OAuth tokens returned after user authorization.
    
    Attributes:
        access_token: Token for making API requests on behalf of the user.
        refresh_token: Token for refreshing the access token when it expires.
    """
    access_token: UserAccessToken
    refresh_token: UserAccessToken | None


class GitHubUser(TypedDict):
    """GitHub user profile information.
    
    Attributes:
        id: Unique identifier for the user.
        login: GitHub username.
        email: User's public email address.
        avatar_url: URL to the user's profile picture.
        name: User's display name.
        company: User's company.
        blog: User's blog or website URL.
        location: User's location.
        bio: User's bio description.
        public_repos: Number of public repositories.
        followers: Number of followers.
        following: Number of users being followed.
        created_at: Account creation timestamp.
        updated_at: Last profile update timestamp.
    """
    id: UserId
    login: str
    email: str | None
    avatar_url: str
    name: str | None
    company: str | None
    blog: str | None
    location: str | None
    bio: str | None
    public_repos: int
    followers: int
    following: int
    created_at: str
    updated_at: str


class GitHubRepoOwner(TypedDict):
    """Repository owner information.
    
    Attributes:
        id: Unique identifier for the owner.
        login: Owner's GitHub username.
        avatar_url: URL to the owner's profile picture.
    """
    id: UserId
    login: str
    avatar_url: str


class GitHubRepo(TypedDict):
    """GitHub repository information.
    
    Attributes:
        id: Unique identifier for the repository.
        name: Repository name.
        full_name: Full repository name (owner/repo).
        private: Whether the repository is private.
        owner: Repository owner information.
        description: Repository description.
        default_branch: Name of the default branch.
        html_url: URL to the repository on GitHub.
        clone_url: URL for cloning the repository.
        created_at: Repository creation timestamp.
        updated_at: Last update timestamp.
        pushed_at: Last push timestamp.
    """
    id: RepositoryId
    name: str
    full_name: str
    private: bool
    owner: GitHubRepoOwner
    description: str | None
    default_branch: str
    html_url: str
    clone_url: str
    created_at: str
    updated_at: str
    pushed_at: str


class GitHubRefObject(TypedDict):
    """Git reference object containing commit information.
    
    Attributes:
        sha: Git commit SHA hash.
        type: Object type (e.g., "commit").
        url: API URL for the object.
    """
    sha: SHA
    type: str
    url: str


class GitHubRef(TypedDict):
    """Git reference (branch or tag) information.
    
    Attributes:
        ref: Full reference name (e.g., "refs/heads/main").
        node_id: GraphQL node ID.
        url: API URL for the reference.
        object: The git object this reference points to.
    """
    ref: str
    node_id: str
    url: str
    object: GitHubRefObject


class GitHubFileContent(TypedDict):
    """File or directory content information from a repository.
    
    Attributes:
        name: File or directory name.
        path: Full path within the repository.
        sha: Git SHA for the content.
        size: File size in bytes.
        type: Content type ("file" or "dir").
        content: Base64 encoded file content (only for files).
        encoding: Content encoding (e.g., "base64").
        html_url: URL to view on GitHub.
        download_url: Direct download URL.
    """
    name: str
    path: str
    sha: SHA
    size: int
    type: str
    content: str | None
    encoding: str | None
    html_url: str
    download_url: str | None


GitHubContent: TypeAlias = GitHubFileContent | list[GitHubFileContent]
"""Repository content - either a single file or a list of directory entries."""