# Comments are generated by Claude

from fastapi import Request, HTTPException, status
from app.utils.auth import validate_session_token
from app.models import User
from app.types import JWT
from app.services.user import get_user_by_id

async def get_current_user(request: Request) -> User:
  """Extract and validate the current user from the session cookie.
  
  This dependency can be injected into any route that requires
  authentication. It validates the JWT session token and fetches
  the full user record from Firestore.
  
  Args:
      request: The incoming HTTP request containing cookies.
      
  Returns:
      The authenticated user's complete data from Firestore.
      
  Raises:
      HTTPException: 401 Unauthorized if:
          - Session token cookie is missing
          - Session token is invalid or expired
          - User ID from token doesn't exist in database
          
  Example:
      @router.get("/protected")
      async def protected_route(current_user: User = Depends(get_current_user)):
          return {"user_id": current_user["id"]}
  """
  session_token: JWT = request.cookies.get("session_token")
  if not session_token:
    raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Session token missing")
  
  try:
    decoded_payload = validate_session_token(session_token)
  except Exception as e:
    raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Session token invalid")
  
  return await get_user_by_id(decoded_payload["sub"])