# Comments are generated by Claude
#comment.py
from app.models.base import BaseModel, datetime
from app.types import UserId

class Comment(BaseModel):
  """Complete comment data returned from the API.
  
  Attributes:
      id: Unique identifier for the comment.
      content: The comment text content.
      author_id: User ID of who wrote the comment.
      created_at: Timestamp when the comment was posted.
      updated_at: Timestamp when the comment was last edited.
  """
  id: str
  content: str
  author_id: UserId
  created_at: datetime
  updated_at: datetime

class CommentCreate(BaseModel):
  """Data required to create a new comment.
  
  The author_id is set by the service layer from the current user.
  
  Attributes:
      content: The comment text content.
  """
  content: str

class CommentUpdate(BaseModel):
  """Data for updating an existing comment. All fields are optional.
  
  Only the comment author can update their comment.
  
  Attributes:
      content: New comment text content.
  """
  content: str | None = None