# Comments are generated by Claude

#enums.py
from enum import IntEnum


class Priority(IntEnum):
  """Issue priority levels.

  Integer values allow for easy comparison and sorting.
  Higher values indicate higher priority.

  Attributes:
      LOWEST: Minimal priority, can be addressed when time permits.
      LOW: Lower priority than normal issues.
      MEDIUM: Default priority for new issues.
      HIGH: Should be addressed soon.
      HIGHEST: Critical priority, requires immediate attention.
  """
  LOWEST = 0
  LOW = 1
  MEDIUM = 2
  HIGH = 3
  HIGHEST = 4