# Comments are generated by Claude
#enums.py
from enum import IntEnum


class Priority(IntEnum):
  """Task priority levels.
  
  Integer values allow for easy comparison and sorting.
  Higher values indicate higher priority.
  
  Attributes:
      LOWEST: Minimal priority, can be addressed when time permits.
      LOW: Lower priority than normal tasks.
      MEDIUM: Default priority for new tasks.
      HIGH: Should be addressed soon.
      HIGHEST: Critical priority, requires immediate attention.
  """
  LOWEST = 0
  LOW = 1
  MEDIUM = 2
  HIGH = 3
  HIGHEST = 4