# Comments are generated by Claude
from app.models.base import BaseModel, datetime
from app.models.enums import Priority
from app.models.github import UserId


class Issue(BaseModel):
  """Complete issue data returned from the API.

  Attributes:
      id: Unique identifier for the issue.
      title: Issue title.
      description: Detailed issue description.
      section_id: ID of the kanban section this issue belongs to.
      assignee_id: User ID of who is assigned to this issue.
      reporter_id: User ID of who created this issue.
      position: Order position within the section for drag-and-drop.
      priority: Issue priority level.
      branch: Git branch name if one was created for this issue.
      branch_url: URL to the branch on GitHub.
      created_at: Timestamp when the issue was created.
      updated_at: Timestamp when the issue was last modified.
  """
  id: str
  title: str
  description: str | None
  section_id: str
  assignee_id: UserId | None
  reporter_id: UserId
  position: int
  priority: Priority
  branch: str | None
  branch_url: str | None
  created_at: datetime
  updated_at: datetime


class IssueCreate(BaseModel):
  """Data required to create a new issue.

  Other fields like reporter_id, position, and priority are set
  by the service layer.

  Attributes:
      title: Issue title.
      section_id: ID of the kanban section to place the issue in.
  """
  title: str
  section_id: str


class IssueUpdate(BaseModel):
  """Data for updating an existing issue. All fields are optional.

  Attributes:
      title: New issue title.
      description: New issue description.
      section_id: ID of section to move issue to.
      position: New position within the section.
      assignee_id: User ID to assign the issue to.
      reporter_id: User ID of the reporter.
      priority: New priority level.
  """
  title: str | None = None
  description: str | None = None
  section_id: str | None = None
  position: int | None = None
  assignee_id: UserId | None = None
  reporter_id: UserId | None = None
  priority: Priority | None = None
