# Comments are generated by Claude
from app.models.base import BaseModel, datetime

class Section(BaseModel):
  """Complete kanban section data returned from the API.
  
  Attributes:
      id: Unique identifier for the section.
      title: Display name of the section (e.g., "TO DO", "IN PROGRESS").
      position: Order position in the kanban board (lower = further left).
      created_at: Timestamp when the section was created.
      updated_at: Timestamp when the section was last modified.
  """
  id: str
  title: str
  position: int
  created_at: datetime
  updated_at: datetime


class SectionCreate(BaseModel):
  """Data required to create a new section.
  
  Position is calculated by the service layer.
  
  Attributes:
      title: Display name for the section.
  """
  title: str


class SectionUpdate(BaseModel):
  """Data for updating an existing section. All fields are optional.
  
  Attributes:
      title: New display name for the section.
      position: New position in the kanban board for reordering.
  """
  title: str | None = None
  position: int | None = None