# Comments are generated by Claude

from app.models.base import BaseModel, datetime
from app.models.enums import Priority
from app.types import UserId


class Task(BaseModel):
  """Complete task data returned from the API.
  
  Attributes:
      id: Unique identifier for the task.
      title: Task title.
      description: Detailed task description.
      section_id: ID of the kanban section this task belongs to.
      assignee_id: User ID of who is assigned to this task.
      reporter_id: User ID of who created this task.
      position: Order position within the section for drag-and-drop.
      priority: Task priority level.
      branch: Git branch name if one was created for this task.
      branch_url: URL to the branch on GitHub.
      created_at: Timestamp when the task was created.
      updated_at: Timestamp when the task was last modified.
  """
  id: str
  title: str
  description: str | None
  section_id: str
  assignee_id: UserId | None
  reporter_id: UserId
  position: int
  priority: Priority
  branch: str | None
  branch_url: str | None
  created_at: datetime
  updated_at: datetime


class TaskCreate(BaseModel):
  """Data required to create a new task.
  
  Other fields like reporter_id, position, and priority are set
  by the service layer.
  
  Attributes:
      title: Task title.
      section_id: ID of the kanban section to place the task in.
  """
  title: str
  section_id: str


class TaskUpdate(BaseModel):
  """Data for updating an existing task. All fields are optional.
  
  Attributes:
      title: New task title.
      description: New task description.
      section_id: ID of section to move task to.
      position: New position within the section.
      assignee_id: User ID to assign the task to.
      reporter_id: User ID of the reporter.
      priority: New priority level.
  """
  title: str | None = None
  description: str | None = None
  section_id: str | None = None
  position: int | None = None
  assignee_id: UserId | None = None
  reporter_id: UserId | None = None
  priority: Priority | None = None