# Comments are generated by Claude
from app.models.base import BaseModel, datetime

from app.types import UserId, UserAccessToken, InstallationId

class UserRead(BaseModel):
  """User data safe to return to clients.
  
  Attributes:
      id: Unique identifier (GitHub user ID).
      github_username: User's GitHub username.
      email: User's email address (may be private).
      avatar_url: URL to the user's GitHub profile picture.
      workspace_ids: List of workspace IDs the user belongs to.
      created_at: Timestamp when the user account was created.
      updated_at: Timestamp when the user was last modified.
  """
  id: UserId
  github_username: str
  email: str | None
  avatar_url: str
  workspace_ids: list[str]
  created_at: datetime
  updated_at: datetime


class User(UserRead):
  """Full user data for internal use only.
  
  Extends UserRead with sensitive fields that should never be
  exposed to clients.
  
  Attributes:
      github_access_token: OAuth token for GitHub API access.
      github_refresh_token: Token for refreshing the access token.
  """
  github_access_token: UserAccessToken
  github_refresh_token: UserAccessToken | None
  installaltion_id: InstallationId | None