# Comments are generated by Claude

from app.models.base import BaseModel, datetime
from app.types import InstallationId, UserId
from typing import TypeAlias

WorkspaceId: TypeAlias = str
"""Unique identifier for a workspace."""

class Workspace(BaseModel):
  """Complete workspace data returned from the API.
  
  Attributes:
      id: Unique identifier for the workspace.
      installation_id: GitHub App installation ID for repository access.
      name: Display name of the workspace.
      join_code: Unique code for users to join this workspace.
      repo_owner: GitHub username or organization that owns the repository.
      repo_name: Name of the connected repository.
      repo_full_name: Full repository name (owner/repo).
      repo_default_branch: Default branch name (e.g., "main").
      member_ids: List of user IDs who belong to this workspace.
      created_by: User ID of the workspace creator.
      created_at: Timestamp when the workspace was created.
      updated_at: Timestamp when the workspace was last modified.
  """
  id: WorkspaceId
  installation_id: InstallationId
  name: str
  join_code: str
  repo_owner: str
  repo_name: str
  repo_full_name: str
  repo_default_branch: str
  member_ids: list[UserId]
  created_by: UserId
  created_at: datetime
  updated_at: datetime

class WorkspaceCreate(BaseModel):
  """Data required to create a new workspace.
  
  Attributes:
      repo_full_name: Full repository name (owner/repo) to connect.
  """
  repo_full_name: str

class WorkspaceUpdate(BaseModel):
  """Data for updating an existing workspace. All fields are optional.
  
  Attributes:
      name: New display name for the workspace.
  """
  name: str | None = None