# ingest-service/src/github/github_client.py
"""
GitHub Client for pushing code changes and documentation
"""
import os
from typing import Dict, Optional
from github import Github, GithubException
from datetime import datetime
import time


class GitHubClient:
    def __init__(self, github_token: Optional[str] = None):
        self.github_token = github_token or os.getenv('GITHUB_TOKEN')
        if not self.github_token:
            raise ValueError("GitHub token required")
        self.github = Github(self.github_token)
        print("✓ GitHub client initialized")

    def get_file_content(self, repo_path: str, file_path: str) -> Optional[str]:
        """
        Fetch current content of a file from GitHub default branch.
        
        Args:
            repo_path: Repository path (owner/repo)
            file_path: Path to file in repo
            
        Returns:
            File content as string, or None if not found
        """
        try:
            if repo_path.startswith('repos/'):
                repo_path = repo_path.replace('repos/', '')
            repo = self.github.get_repo(repo_path)
            branch = repo.default_branch
            contents = repo.get_contents(file_path, ref=branch)
            return contents.decoded_content.decode('utf-8')
        except Exception as e:
            print(f"⚠️  Could not fetch {file_path}: {e}")
            return None

    def create_branch_and_push_code(self, repo_path: str, file_path: str,
                                    new_content: str, instruction: str,
                                    branch_name: Optional[str] = None) -> Dict:
        try:
            if repo_path.startswith('repos/'):
                repo_path = repo_path.replace('repos/', '')

            print(f"📦 Accessing repository: {repo_path}")
            repo = self.github.get_repo(repo_path)
            print(f"✓ Repository found: {repo.full_name}")

            if not repo.permissions.push:
                return {'success': False, 'error': 'No push permissions for this repository'}

            if not branch_name:
                timestamp = int(time.time())
                safe_instruction = instruction.lower()[:30].replace(" ", "-")
                safe_instruction = "".join(c for c in safe_instruction if c.isalnum() or c == "-")
                branch_name = f"otto-edit-{safe_instruction}-{timestamp}"

            print(f"📌 Branch name: {branch_name}")

            default_branch = repo.default_branch
            source_branch = repo.get_branch(default_branch)
            print(f"✓ Base branch: {default_branch} (SHA: {source_branch.commit.sha[:8]})")

            try:
                repo.create_git_ref(
                    ref=f"refs/heads/{branch_name}",
                    sha=source_branch.commit.sha
                )
                print(f"✓ Created branch: {branch_name}")
            except GithubException as e:
                if e.status == 422:
                    print(f"⚠️  Branch {branch_name} already exists, using it")
                else:
                    raise

            commit_message = f"Otto AI Edit: {instruction}\n\nAutomated code modification by Otto AI assistant."

            try:
                file_contents = repo.get_contents(file_path, ref=default_branch)
                print(f"✓ Found existing file: {file_path}")
                result = repo.update_file(
                    path=file_path,
                    message=commit_message,
                    content=new_content,
                    sha=file_contents.sha,
                    branch=branch_name
                )
                print(f"✓ Updated file on branch {branch_name}")

            except GithubException as e:
                if e.status == 404:
                    print(f"📝 Creating new file: {file_path}")
                    result = repo.create_file(
                        path=file_path,
                        message=commit_message,
                        content=new_content,
                        branch=branch_name
                    )
                    print(f"✓ Created new file on branch {branch_name}")
                else:
                    raise

            pr_title = f"🤖 Otto AI: {instruction[:50]}"
            pr_body = f"""## 🤖 Automated Code Edit by Otto AI

**Instruction:** {instruction}

**Modified File:** `{file_path}`

**Branch:** `{branch_name}`

---

### 📝 Changes Summary

{self._extract_change_summary(new_content)}

### ✅ Review Instructions

1. Review the changes in `{file_path}`
2. Run tests to ensure functionality
3. Merge if changes are satisfactory

---

*This pull request was automatically generated by [Otto AI](https://github.com/otto-pm/otto)*
"""

            try:
                pr = repo.create_pull(
                    title=pr_title,
                    body=pr_body,
                    head=branch_name,
                    base=default_branch
                )
                print(f"✓ Pull request created: #{pr.number}")
                print(f"  URL: {pr.html_url}")
                return {
                    'success': True,
                    'branch': branch_name,
                    'commit_sha': result['commit'].sha,
                    'pr_url': pr.html_url,
                    'pr_number': pr.number,
                    'file_path': file_path,
                    'base_branch': default_branch
                }

            except GithubException as e:
                if e.status == 422:
                    existing_prs = repo.get_pulls(state='open', head=f"{repo.owner.login}:{branch_name}")
                    pr_list = list(existing_prs)
                    if pr_list:
                        existing_pr = pr_list[0]
                        print(f"⚠️  PR already exists: {existing_pr.html_url}")
                        return {
                            'success': True,
                            'branch': branch_name,
                            'commit_sha': result['commit'].sha,
                            'pr_url': existing_pr.html_url,
                            'pr_number': existing_pr.number,
                            'message': 'Changes committed, PR already exists'
                        }
                    else:
                        return {
                            'success': True,
                            'branch': branch_name,
                            'commit_sha': result['commit'].sha,
                            'pr_url': None,
                            'message': f'Changes committed to branch {branch_name}, but PR creation failed'
                        }
                else:
                    raise

        except GithubException as e:
            error_msg = f"GitHub API error: {e.data.get('message', str(e)) if hasattr(e, 'data') else str(e)}"
            print(f"❌ {error_msg}")
            return {'success': False, 'error': error_msg}
        except Exception as e:
            print(f"❌ Error: {e}")
            return {'success': False, 'error': str(e)}

    def push_documentation(self, repo_path: str, doc_content: str,
                          doc_name: str, doc_type: str = 'api',
                          create_pr: bool = True) -> Dict:
        try:
            if repo_path.startswith('repos/'):
                repo_path = repo_path.replace('repos/', '')
            repo = self.github.get_repo(repo_path)

            if doc_type == 'readme':
                file_path = 'README.md'
            else:
                safe_name = doc_name.lower().replace(" ", "-")
                safe_name = "".join(c for c in safe_name if c.isalnum() or c in ["-", "_"])
                file_path = f"docs/{doc_type}/{safe_name}.md"

            print(f"📄 Documentation path: {file_path}")
            return self.create_branch_and_push_code(
                repo_path=repo_path,
                file_path=file_path,
                new_content=doc_content,
                instruction=f"Add {doc_type} documentation for {doc_name}"
            )

        except Exception as e:
            print(f"❌ Error pushing documentation: {e}")
            return {'success': False, 'error': str(e)}

    def _extract_change_summary(self, content: str, max_lines: int = 10) -> str:
        lines = content.split('\n')
        if len(lines) <= max_lines:
            return f"```\n{content}\n```"
        else:
            preview = '\n'.join(lines[:max_lines])
            return f"```\n{preview}\n...\n({len(lines) - max_lines} more lines)\n```"