# ingest-service/src/utils/file_manager.py
"""
File manager for saving documentation and code edits locally
"""
import os
from pathlib import Path
from datetime import datetime
from typing import Optional


class DocumentationManager:
    """Manage documentation and code files locally"""
    
    def __init__(self, output_dir: str = "./output"):
        """
        Initialize file manager
        
        Args:
            output_dir: Base directory for all output files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        print(f"✓ Output directory: {self.output_dir.absolute()}")
    
    def save_documentation(self, content: str, name: str, doc_type: str,
                          repo_path: Optional[str] = None) -> str:
        """
        Save documentation to a file
        
        Args:
            content: Documentation content
            name: Document name
            doc_type: Type (api, user_guide, technical, readme)
            repo_path: Repository path (e.g., 'repos/otto-pm/otto')
            
        Returns:
            Path to saved file
        """
        # Create subdirectory for documentation
        docs_dir = self.output_dir / "documentation" / doc_type
        docs_dir.mkdir(parents=True, exist_ok=True)
        
        # Sanitize filename
        safe_name = name.lower().replace(" ", "-")
        safe_name = "".join(c for c in safe_name if c.isalnum() or c in ["-", "_"])
        
        # Add timestamp
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        
        # Create filename
        if repo_path:
            repo_name = repo_path.replace('repos/', '').replace("/", "-")
            filename = f"{repo_name}_{safe_name}_{timestamp}.md"
        else:
            filename = f"{safe_name}_{timestamp}.md"
        
        filepath = docs_dir / filename
        
        # Write content
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"# {name}\n\n")
            f.write(f"*Generated by Otto AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n\n")
            f.write(f"---\n\n")
            f.write(content)
        
        print(f"✓ Documentation saved: {filepath}")
        return str(filepath)
    
    def save_edited_code(self, content: str, original_file: str,
                        repo_path: str, instruction: str) -> str:
        """
        Save edited code locally
        
        Args:
            content: Edited code content
            original_file: Original file path
            repo_path: Repository path
            instruction: Edit instruction
            
        Returns:
            Path to saved file
        """
        # Create edits directory
        edits_dir = self.output_dir / "code_edits"
        edits_dir.mkdir(parents=True, exist_ok=True)
        
        # Get file extension
        ext = os.path.splitext(original_file)[1] or '.txt'
        
        # Create filename
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        repo_name = repo_path.replace('repos/', '').replace("/", "-")
        safe_file = original_file.replace("/", "-").replace(".", "-")
        filename = f"{repo_name}_{safe_file}_{timestamp}{ext}"
        
        filepath = edits_dir / filename
        
        # Write content with metadata header
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"# Edited by Otto AI\n")
            f.write(f"# Original file: {original_file}\n")
            f.write(f"# Repository: {repo_path}\n")
            f.write(f"# Instruction: {instruction}\n")
            f.write(f"# Timestamp: {timestamp}\n")
            f.write(f"# {'='*60}\n\n")
            f.write(content)
        
        print(f"✓ Edited code saved: {filepath}")
        return str(filepath)
    
    def save_completion(self, content: str, filename: str) -> str:
        """
        Save code completion to a file
        
        Args:
            content: Completion content
            filename: Suggested filename
            
        Returns:
            Path to saved file
        """
        # Create completions directory
        completions_dir = self.output_dir / "completions"
        completions_dir.mkdir(parents=True, exist_ok=True)
        
        # Add timestamp
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        base, ext = os.path.splitext(filename)
        filename_with_time = f"{base}_{timestamp}{ext}"
        
        filepath = completions_dir / filename_with_time
        
        # Write content
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"# Code completion by Otto AI\n")
            f.write(f"# Generated: {timestamp}\n")
            f.write(f"# {'='*60}\n\n")
            f.write(content)
        
        print(f"✓ Completion saved: {filepath}")
        return str(filepath)