// Mock data for local testing

// Mock data for local testing
import type { IssueType } from './types';

export const mockUsers = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john@example.com",
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: "user-2",
    name: "Jane Smith",
    email: "jane@example.com",
    avatar: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: "user-3",
    name: "Bob Wilson",
    email: "bob@example.com",
    avatar: "https://i.pravatar.cc/150?img=3",
  },
];

export const mockSprints = [
  {
    id: "sprint-1",
    name: "Sprint 1",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-14"),
    status: "ACTIVE",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "sprint-2",
    name: "Sprint 2",
    startDate: new Date("2024-01-15"),
    endDate: new Date("2024-01-28"),
    status: "PLANNED",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

export const mockIssues = [
  {
    id: "issue-1",
    key: "SAMP-1",
    name: "Set up project repository",
    description: JSON.stringify({
      root: {
        children: [
          {
            children: [{ detail: 0, format: 0, mode: "normal", style: "", text: "Initialize the project with proper folder structure", type: "text", version: 1 }],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "root",
        version: 1,
      },
    }),
    status: "DONE",
    type: "TASK",
    priority: "HIGH",
    sprintPosition: 0,
    boardPosition: 0,
    reporterId: "user-1",
    assigneeId: "user-1",
    parentId: null,
    sprintId: "sprint-1",
    sprintColor: "#4CAF50",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-03"),
    sprintIsActive: true,
    parent: null,
    assignee: mockUsers[0],
    reporter: mockUsers[0],
    children: [],
  },
  {
    id: "issue-2",
    key: "SAMP-2",
    name: "Design database schema",
    description: JSON.stringify({
      root: {
        children: [
          {
            children: [{ detail: 0, format: 0, mode: "normal", style: "", text: "Create ERD and design the database structure", type: "text", version: 1 }],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "root",
        version: 1,
      },
    }),
    status: "IN_PROGRESS",
    type: "TASK",
    priority: "HIGH",
    sprintPosition: 1,
    boardPosition: 1,
    reporterId: "user-1",
    assigneeId: "user-2",
    parentId: null,
    sprintId: "sprint-1",
    sprintColor: "#4CAF50",
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-05"),
    sprintIsActive: true,
    parent: null,
    assignee: mockUsers[1],
    reporter: mockUsers[0],
    children: [],
  },
  {
    id: "issue-3",
    key: "SAMP-3",
    name: "Build authentication system",
    description: JSON.stringify({
      root: {
        children: [
          {
            children: [{ detail: 0, format: 0, mode: "normal", style: "", text: "Implement user login and registration", type: "text", version: 1 }],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "root",
        version: 1,
      },
    }),
    status: "TODO",
    type: "STORY",
    priority: "MEDIUM",
    sprintPosition: 2,
    boardPosition: 2,
    reporterId: "user-2",
    assigneeId: "user-3",
    parentId: null,
    sprintId: "sprint-1",
    sprintColor: "#4CAF50",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
    sprintIsActive: true,
    parent: null,
    assignee: mockUsers[2],
    reporter: mockUsers[1],
    children: [],
  },
  {
    id: "issue-4",
    key: "SAMP-4",
    name: "Fix navigation bug",
    description: JSON.stringify({
      root: {
        children: [
          {
            children: [{ detail: 0, format: 0, mode: "normal", style: "", text: "Navigation menu doesn't close on mobile", type: "text", version: 1 }],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "root",
        version: 1,
      },
    }),
    status: "TODO",
    type: "BUG",
    priority: "HIGH",
    sprintPosition: 3,
    boardPosition: 3,
    reporterId: "user-3",
    assigneeId: null,
    parentId: null,
    sprintId: null, // Backlog item
    sprintColor: null,
    createdAt: new Date("2024-01-04"),
    updatedAt: new Date("2024-01-04"),
    sprintIsActive: false,
    parent: null,
    assignee: null,
    reporter: mockUsers[2],
    children: [],
  },
  {
    id: "issue-5",
    key: "SAMP-5",
    name: "Add dark mode support",
    description: JSON.stringify({
      root: {
        children: [
          {
            children: [{ detail: 0, format: 0, mode: "normal", style: "", text: "Implement dark mode toggle and theme switching", type: "text", version: 1 }],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "root",
        version: 1,
      },
    }),
    status: "TODO",
    type: "TASK",
    priority: "LOW",
    sprintPosition: 4,
    boardPosition: 4,
    reporterId: "user-1",
    assigneeId: null,
    parentId: null,
    sprintId: null, // Backlog item
    sprintColor: null,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
    sprintIsActive: false,
    parent: null,
    assignee: null,
    reporter: mockUsers[0],
    children: [],
  },
];

export const mockProject = {
  id: "project-1",
  name: "Sample Project",
  key: "SAMP",
  description: "This is a sample project for testing the JIRA clone UI",
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
};

export const mockComments = [
  {
    id: "comment-1",
    issueId: "issue-2",
    authorId: "user-1",
    content: JSON.stringify({
      root: {
        children: [
          {
            children: [{ detail: 0, format: 0, mode: "normal", style: "", text: "This is looking good! Keep up the progress.", type: "text", version: 1 }],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "paragraph",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "root",
        version: 1,
      },
    }),
    createdAt: new Date("2024-01-04"),
    updatedAt: new Date("2024-01-04"),
    isEdited: false,
    author: mockUsers[0],
  },
];