# Comments are generated by Claude

import httpx
import jwt
import time
from fastapi import status
from httpx import Response
from app.config import (
  GITHUB_APP_ID,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  GITHUB_PRIVATE_KEY,
  GITHUB_CALLBACK_URL
)
from app.types import (
  JWT,
  InstallationToken,
  InstallationId,
  OAuthUrl,
  OAuthCode,
  OAuthState,
  SHA,
  UserAccessToken,
  UserTokens,
  GitHubUser,
  GitHubRepo,
  GitHubRepoOwner,
  GitHubRef,
  GitHubFileContent,
  GitHubContent,
  SessionPayload,
  GitHubAppJWTPayload
)

class GitHubAPIError(Exception):
  """Exception raised when a GitHub API request fails.
  
  Attributes:
      message: Error message from the GitHub API.
      status_code: HTTP status code returned by GitHub.
  """
  def __init__(self, message: str, status_code: int):
    self.message = message
    self.status_code = status_code
    super().__init__(self.message)

def handle_error(response: Response, expected_status_code: int) -> None:
  """Check response status and raise an exception if unexpected.
  
  Args:
      response: The HTTP response from GitHub.
      expected_status_code: The expected successful status code.
      
  Raises:
      GitHubAPIError: If the response status doesn't match expected.
  """
  if response.status_code != expected_status_code:
    error_data = response.json()
    raise GitHubAPIError(error_data.get("message"), response.status_code)

def generate_jwt() -> JWT:
  """Generate a JWT for GitHub App authentication.
  
  Creates a signed JWT using the app's private key, valid for 10 minutes.
  Used to authenticate as the GitHub App itself.
  
  Returns:
      A signed JWT string for GitHub App authentication.
  """
  payload: GitHubAppJWTPayload = {
    "iat": int(time.time()) - 60,
    "exp": int(time.time()) + 600,
    "iss": GITHUB_APP_ID
  }
  token: JWT = jwt.encode(payload, GITHUB_PRIVATE_KEY, algorithm="RS256")
  return token

async def get_installation_token(installation_id: InstallationId) -> InstallationToken:
  """Get an access token for a specific GitHub App installation.
  
  Exchanges the app JWT for an installation-specific token that can
  access the repositories where the app is installed.
  
  Args:
      installation_id: The GitHub App installation ID.
      
  Returns:
      An installation access token valid for 1 hour.
      
  Raises:
      GitHubAPIError: If the token request fails.
  """
  token: JWT = generate_jwt()
  url = f"https://api.github.com/app/installations/{installation_id}/access_tokens"
  headers = {
    "Authorization": f"Bearer {token}",
    "Accept": "application/vnd.github+json"
  }
  async with httpx.AsyncClient() as client:
    response = await client.post(url, headers=headers)
    handle_error(response, status.HTTP_201_CREATED)
    data = response.json()
    return data["token"]

def build_oauth_url(state: OAuthState) -> OAuthUrl:
  """Build the GitHub OAuth authorization URL.
  
  Constructs the URL to redirect users to for GitHub login.
  
  Args:
      state: CSRF protection token to verify on callback.
      
  Returns:
      The full GitHub OAuth authorization URL.
  """
  url = "https://github.com/login/oauth/authorize"
  url += f"?client_id={GITHUB_CLIENT_ID}"
  url += f"&redirect_uri={GITHUB_CALLBACK_URL}"
  url += f"&state={state}"
  return url

async def get_user_access_token(code: OAuthCode) -> UserTokens:
  """Exchange an authorization code for user access tokens.
  
  Called after the user authorizes the app on GitHub's OAuth page.
  
  Args:
      code: The authorization code from the OAuth callback.
      
  Returns:
      Dictionary containing access_token and refresh_token.
      
  Raises:
      GitHubAPIError: If the token exchange fails.
  """
  url = "https://github.com/login/oauth/access_token"
  url += f"?client_id={GITHUB_CLIENT_ID}"
  url += f"&client_secret={GITHUB_CLIENT_SECRET}"
  url += f"&code={code}"
  headers = {
    "Accept": "application/json"
  }
  async with httpx.AsyncClient() as client:
    response = await client.post(url, headers=headers)
    handle_error(response, status.HTTP_200_OK)
    data = response.json()
    return {
      "access_token": data["access_token"],
      "refresh_token": data.get("refresh_token")
    }

async def get_user_profile(user_access_token: UserAccessToken) -> GitHubUser:
  """Fetch the authenticated user's GitHub profile.
  
  Args:
      user_access_token: OAuth access token for the user.
      
  Returns:
      The user's GitHub profile information.
      
  Raises:
      GitHubAPIError: If the profile request fails.
  """
  url = "https://api.github.com/user"
  headers = {
    "Authorization": f"Bearer {user_access_token}"
  }
  async with httpx.AsyncClient() as client:
    response = await client.get(url, headers=headers)
    handle_error(response, status.HTTP_200_OK)
    return response.json()

async def get_repository_details(installation_token: InstallationToken, owner: str, repository: str) -> GitHubRepo:
  """Get detailed information about a repository.
  
  Args:
      installation_token: GitHub App installation access token.
      owner: Repository owner username or organization.
      repository: Repository name.
      
  Returns:
      Repository details including default branch and URLs.
      
  Raises:
      GitHubAPIError: If the request fails.
  """
  url = f"https://api.github.com/repos/{owner}/{repository}"
  headers = {
    "Authorization": f"Bearer {installation_token}"
  }
  async with httpx.AsyncClient() as client:
    response = await client.get(url, headers=headers)
    handle_error(response, status.HTTP_200_OK)
    return response.json()

async def get_repository_contents(installation_token: InstallationToken, owner: str, repository: str, path: str = "") -> GitHubContent:
  """Get contents of a file or directory in a repository.
  
  For files, returns the file metadata and base64-encoded content.
  For directories, returns a list of entries.
  
  Args:
      installation_token: GitHub App installation access token.
      owner: Repository owner username or organization.
      repository: Repository name.
      path: Path to file or directory (empty string for root).
      
  Returns:
      File content object or list of directory entries.
      
  Raises:
      GitHubAPIError: If the request fails.
  """
  url = f"https://api.github.com/repos/{owner}/{repository}/contents/{path}"
  headers = {
    "Authorization": f"Bearer {installation_token}"
  }
  async with httpx.AsyncClient() as client:
    response = await client.get(url, headers=headers)
    handle_error(response, status.HTTP_200_OK)
    return response.json()
  
async def list_installation_repositories(installation_token: InstallationToken) -> list[GitHubRepo]:
  """List all repositories accessible to a GitHub App installation.
  
  Args:
      installation_token: Access token for the installation.
      
  Returns:
      List of all repositories the installation can access.
      
  Raises:
      GitHubAPIError: If the request fails.
  """
  all_repos = []
  page = 1
  per_page = 100
  
  headers = {
    "Authorization": f"Bearer {installation_token}",
    "Accept": "application/vnd.github+json"
  }
  
  async with httpx.AsyncClient() as client:
    while True:
      url = f"https://api.github.com/installation/repositories?per_page={per_page}&page={page}"
      response = await client.get(url, headers=headers)
      handle_error(response, status.HTTP_200_OK)
      
      data = response.json()
      repos = data.get("repositories", [])
      
      if not repos:
        break
          
      all_repos.extend(repos)
      
      if len(repos) < per_page:
        break
          
      page += 1
  
  return all_repos

async def get_default_branch_sha(installation_token: InstallationToken, owner: str, repository: str, branch: str) -> SHA:
  """Get the latest commit SHA of a branch.
  
  Used to get the base commit when creating a new branch.
  
  Args:
      installation_token: GitHub App installation access token.
      owner: Repository owner username or organization.
      repository: Repository name.
      branch: Branch name to get the SHA for.
      
  Returns:
      The SHA hash of the branch's HEAD commit.
      
  Raises:
      GitHubAPIError: If the request fails.
  """
  url = f"https://api.github.com/repos/{owner}/{repository}/git/ref/heads/{branch}"
  headers = {
    "Authorization": f"Bearer {installation_token}"
  }
  async with httpx.AsyncClient() as client:
    response = await client.get(url, headers=headers)
    handle_error(response, status.HTTP_200_OK)
    data = response.json()
    return data["object"]["sha"]

async def create_branch(installation_token: InstallationToken, owner: str, repository: str, branch_name: str, sha: SHA) -> GitHubRef:
  """Create a new branch in a repository.
  
  Args:
      installation_token: GitHub App installation access token.
      owner: Repository owner username or organization.
      repository: Repository name.
      branch_name: Name for the new branch.
      sha: Commit SHA to branch from.
      
  Returns:
      The created git reference object.
      
  Raises:
      GitHubAPIError: If branch creation fails (e.g., already exists).
  """
  url = f"https://api.github.com/repos/{owner}/{repository}/git/refs"
  headers = {
    "Authorization": f"Bearer {installation_token}"
  }
  body = {
    "ref": f"refs/heads/{branch_name}",
    "sha": sha
  }
  async with httpx.AsyncClient() as client:
    response = await client.post(url, headers=headers, json=body)
    handle_error(response, status.HTTP_201_CREATED)
    return response.json()